[project]
name = "engineering_tem"
version = "0.1.0"
description = "engineering_tem using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.14.4"
]

[project.scripts]
engineering_tem = "engineering_tem.main:run"
run_crew = "engineering_tem.main:run"
train = "engineering_tem.main:train"
replay = "engineering_tem.main:replay"
test = "engineering_tem.main:test"
run_with_trigger = "engineering_tem.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
